"""Postgres wrapper for firewall rule storage (ported from sqlite3 — see
memory/project notes for the migration).

No ORM on purpose — same reasoning as before: a handful of tables, a
small dependency footprint. `?` placeholders became `%s` (psycopg2/
libpq convention); `AUTOINCREMENT` became `GENERATED BY DEFAULT AS IDENTITY`;
timestamp columns stayed TEXT (not TIMESTAMPTZ) storing the exact same
'YYYY-MM-DD HH:MM:SS' strings the rest of the app (vpnlog.py,
ingest_logs.py) already formats/compares as strings — switching to a
native timestamp type would have meant auditing every comparison site
across the codebase for a port that doesn't need it.

_PGConnection below exists because psycopg2, unlike sqlite3, has no
connection-level .execute() convenience — every call site in this file
(and in firewall.py, which receives a raw connection from
locked_transaction()) calls conn.execute(...) directly. This adds just
enough of that surface back so porting stayed a placeholder-syntax
change, not a structural rewrite of every call site.
"""
import contextlib
import secrets
from datetime import datetime, timedelta

import psycopg2
import psycopg2.errors
from psycopg2.extras import RealDictCursor
from werkzeug.security import check_password_hash, generate_password_hash

import config


class _PGConnection:
    def __init__(self, pg_conn):
        self._conn = pg_conn

    def execute(self, sql, params=None):
        cur = self._conn.cursor()
        cur.execute(sql, params if params is not None else ())
        return cur

    def executemany(self, sql, seq_of_params):
        cur = self._conn.cursor()
        cur.executemany(sql, seq_of_params)
        return cur

    def commit(self):
        self._conn.commit()

    def rollback(self):
        self._conn.rollback()

    def close(self):
        self._conn.close()

    def cursor(self):
        return self._conn.cursor()


def _connect():
    return psycopg2.connect(
        host=config.DB_HOST,
        port=config.DB_PORT,
        dbname=config.DB_NAME,
        user=config.DB_USER,
        password=config.DB_PASSWORD,
        cursor_factory=RealDictCursor,
    )


# Fixed, arbitrary key for the advisory lock below — any int64 works, this
# one has no special meaning beyond being unlikely to collide with some
# other, unrelated advisory lock this app might take out in the future.
_LOCKED_TRANSACTION_LOCK_KEY = 918273645


@contextlib.contextmanager
def locked_transaction():
    """Yields a connection for callers whose read-check-write sequence
    must be atomic against a *second concurrent caller doing the same
    kind of check* — e.g. "is this the last admin?", "would this rule
    change lock the admin out?". A plain get_conn()-per-call is fine for
    a single read or write, but a read-then-decide-then-write guard
    built from two separate calls has a real gap: two near-simultaneous
    requests can each read the same pre-write state before either
    commits, both pass their own check, and both proceed.

    First porting attempt used Postgres's row-level SELECT ... FOR UPDATE,
    matched to whatever rows each caller's specific check reads — real
    bug, caught live by this file's own concurrency regression tests:
    several call sites in firewall.py never got FOR UPDATE added (the
    dialect port that touched those files was a placeholder-syntax pass,
    not a locking-semantics audit), and set_client_block's "does a block
    row already exist" check has no row to lock *at all* when it doesn't
    exist yet — a race there can't be closed by locking rows that aren't
    there. Switched to a single pg_advisory_xact_lock instead: one fixed
    key, held for the whole transaction, released automatically on
    commit or rollback. Coarser than per-row locking, but this app's
    write volume (a handful of admins/moderators, not a public write-
    heavy API) makes that a non-issue, and it's a far more faithful port
    of what SQLite's BEGIN IMMEDIATE actually guaranteed here anyway — a
    single writer for the whole database, not per-row — while removing
    an entire class of "forgot to lock the right rows" bug outright.

    lock_timeout (5s, matching SQLite's own default busy_timeout) means
    a caller blocked behind someone else's still-open transaction fails
    with psycopg2.errors.LockNotAvailable instead of hanging forever —
    callers catch this the same way they used to catch
    sqlite3.OperationalError. (pg_advisory_xact_lock itself ignores
    lock_timeout unless its own statement_timeout-style setting applies
    — SET LOCAL lock_timeout does cover advisory locks specifically, per
    Postgres's own docs, so this still works as intended.)

    Commits on clean exit (including a plain `return` from inside the
    `with` block); rolls back and re-raises on any exception."""
    pg_conn = _connect()
    conn = _PGConnection(pg_conn)
    try:
        conn.execute("SET LOCAL lock_timeout = '5s'")
        conn.execute("SELECT pg_advisory_xact_lock(%s)", (_LOCKED_TRANSACTION_LOCK_KEY,))
        yield conn
        conn.commit()
    except Exception:
        conn.rollback()
        raise
    finally:
        conn.close()


SCHEMA = """
CREATE TABLE IF NOT EXISTS firewall_rules (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    kind TEXT NOT NULL,          -- 'forward' | 'input' | 'portforward' | 'masquerade' | 'client_block'
    action TEXT,                 -- 'ACCEPT' | 'DROP' | 'MASQUERADE'
    protocol TEXT,               -- 'tcp' | 'udp' | 'all'
    src TEXT,
    dst TEXT,
    dport TEXT,
    ext_port TEXT,
    target_ip TEXT,
    target_port TEXT,
    ext_iface TEXT,
    out_iface TEXT,
    snat_ip TEXT,
    client_name TEXT,
    client_ip TEXT,
    comment TEXT,
    source TEXT NOT NULL DEFAULT 'webui',  -- 'webui' | 'cli' (discovered from a manually-run iptables command)
    enabled INTEGER NOT NULL DEFAULT 1,
    position DOUBLE PRECISION,    -- display/apply order among rules sharing a chain — see firewall.py's _rebuild_chain
    created_at TEXT DEFAULT to_char(now(), 'YYYY-MM-DD HH24:MI:SS')
);

CREATE TABLE IF NOT EXISTS audit_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ts TEXT DEFAULT to_char(now(), 'YYYY-MM-DD HH24:MI:SS'),
    actor TEXT,
    action TEXT NOT NULL,
    target TEXT,
    result TEXT NOT NULL,   -- 'ok' | 'error'
    detail TEXT
);

-- Login rate-limiting. A plain in-process counter doesn't work here:
-- gunicorn runs 2 worker processes (separate OS processes, no shared
-- memory), so a counter living in one worker's memory would only ever
-- see roughly half of an attacker's requests. This table is the shared
-- state both workers see.
CREATE TABLE IF NOT EXISTS login_failures (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ip TEXT NOT NULL,
    ts TEXT DEFAULT to_char(now(), 'YYYY-MM-DD HH24:MI:SS')
);

-- No 'active' column on purpose: CRUD means a real delete, not a
-- soft-disable flag. role: 'admin' (full access) | 'moderator' (client
-- control + Logs' Client Sessions/Auth tabs only, view-only on this table)
-- — see app/auth.py's admin_required.
CREATE TABLE IF NOT EXISTS users (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username TEXT NOT NULL UNIQUE,
    password_hash TEXT NOT NULL,
    role TEXT NOT NULL DEFAULT 'admin',
    -- Bumped on every successful login (browser or API) — embedded in
    -- that login's JWT as the "gen" claim. Any token whose "gen" doesn't
    -- match the CURRENT value here is treated as logged out, which is
    -- what makes a fresh login elsewhere immediately invalidate every
    -- older session/token for this same account, without needing to
    -- reach out and kill them directly — see auth.py's
    -- load_user_from_jwt_cookie and __init__.py's blocklist_loader.
    session_generation INTEGER NOT NULL DEFAULT 0,
    created_at TEXT DEFAULT to_char(now(), 'YYYY-MM-DD HH24:MI:SS')
);

-- Destination IP -> organization, for the Traffic log (see
-- app/iplookup.py). org-to-IP-block ownership essentially never changes,
-- so this is a permanent cache, not a TTL'd one — org IS NULL means "we
-- already looked this IP up and found nothing usable," which is itself
-- worth remembering so a persistently-unresolvable IP only ever costs one
-- real WHOIS query, not one per page load.
CREATE TABLE IF NOT EXISTS ip_org_cache (
    ip TEXT PRIMARY KEY,
    org TEXT,
    looked_up_at TEXT DEFAULT to_char(now(), 'YYYY-MM-DD HH24:MI:SS')
);

-- Structured OpenVPN journal lines, ingested periodically by
-- deploy/ingest_logs.py (see that script and
-- pivpn-webui-log-helper.sh's openvpn-tail action) instead of vpnlog.py
-- regex-parsing raw journal text on every single page load — measured at
-- ~1.5s for a real 7-day/13k-line volume on a live server, once someone
-- actually wants a week of history rather than the original 3-day window.
-- Stores every line, not just matched connect/disconnect ones — the VPN
-- Sessions tab deliberately also shows unrecognized lines as event='other'
-- with the raw text in `detail` (a diagnostic fallback for when this
-- server's OpenVPN log format doesn't match CONNECT_RE/DISCONNECT_RE), and
-- losing that by only storing matches would be a real feature regression,
-- not just an implementation-detail change.
-- The UNIQUE constraint is a deliberate belt-and-suspenders against
-- ingest_logs.py ever reprocessing the same journal line twice (confirmed
-- live: journalctl --cursor-file can re-emit the last-seen entry on the
-- very next invocation) — ON CONFLICT DO NOTHING makes a duplicate ingest
-- a no-op instead of a duplicate row.
CREATE TABLE IF NOT EXISTS vpn_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ts TEXT NOT NULL,                    -- 'YYYY-MM-DD HH:MM:SS', same format used everywhere else in this app
    event TEXT NOT NULL,                 -- 'connected' | 'disconnected' | 'other'
    client TEXT NOT NULL DEFAULT '',
    address TEXT NOT NULL DEFAULT '',
    detail TEXT NOT NULL DEFAULT '',     -- only populated for event='other'
    real_address TEXT,                   -- only populated for event='connected' behind the relay
    UNIQUE (ts, event, client, address, detail)
);
CREATE INDEX IF NOT EXISTS idx_vpn_events_ts ON vpn_events(ts);

-- Structured per-flow traffic rows, same ingestion story as vpn_events
-- above but for the Traffic tab (see setup-traffic-log.sh's mangle-table
-- LOG rule) — measured at ~4s+ for a real 7-day volume at this app's
-- current traffic rate (thousands of flows/day), the clearest case for
-- moving off live per-request parsing. dst_org/client are resolved once,
-- at ingest time (via app/iplookup.py's same WHOIS+cache path, and
-- app/vpnlog.py's _client_ip_map()) rather than per page view — ingestion
-- isn't on any HTTP request's critical path, so there's no reason to defer
-- that work the way the request-time code used to.
CREATE TABLE IF NOT EXISTS traffic_flows (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ts TEXT NOT NULL,
    src TEXT NOT NULL,
    dst TEXT NOT NULL,
    dst_org TEXT,           -- NULL = private/reserved address, or a WHOIS lookup that found nothing
    client TEXT,            -- resolved client name at ingest time; NULL if src didn't map to a known client
    proto TEXT NOT NULL,
    sport TEXT,
    dport TEXT,
    in_if TEXT,
    out_if TEXT,
    UNIQUE (ts, src, dst, proto, sport, dport)
);
CREATE INDEX IF NOT EXISTS idx_traffic_flows_ts ON traffic_flows(ts);

-- Whole-system journal lines, ingested incrementally by
-- deploy/ingest_logs.py (system-tail action) instead of the Logs page's
-- System tab live-fetching a full journalctl window on every request —
-- that live fetch is what a real 7-day/60k-line pull turned into an
-- 8+MB payload for, the same order of magnitude that motivated
-- vpn_events/traffic_flows moving off live parsing earlier. process is
-- split out from message (see vpnlog.py's journal-line parsing) so the
-- Logs page can show/search it as its own column instead of it being
-- buried in free text on every row.
CREATE TABLE IF NOT EXISTS system_log_lines (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ts TEXT NOT NULL,
    process TEXT NOT NULL DEFAULT '',
    message TEXT NOT NULL,
    UNIQUE (ts, process, message)
);
CREATE INDEX IF NOT EXISTS idx_system_log_lines_ts ON system_log_lines(ts);

-- Hub/agent split (see config.py's HUB_MODE) — one row per remote PiVPN
-- box the hub can dispatch run_root/run_pivpn/read_file calls to over
-- hub_gateway.py's WebSocket. token_hash only, never the raw token, same
-- reasoning as users.password_hash above; the raw token is shown once at
-- `manage_servers.py register` time and never stored anywhere again.
CREATE TABLE IF NOT EXISTS servers (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL UNIQUE,
    token_hash TEXT NOT NULL,
    token_expires_at TEXT,
    created_at TEXT DEFAULT to_char(now(), 'YYYY-MM-DD HH24:MI:SS'),
    last_seen_at TEXT
);
"""


def get_conn():
    return _PGConnection(_connect())


# Columns added after the initial release — CREATE TABLE IF NOT EXISTS won't
# retrofit these onto a database that already exists, so migrate explicitly.
# Keyed by table, then column -> DDL.
_MIGRATIONS = {
    "firewall_rules": {
        "out_iface": "ALTER TABLE firewall_rules ADD COLUMN out_iface TEXT",
        "source": "ALTER TABLE firewall_rules ADD COLUMN source TEXT NOT NULL DEFAULT 'webui'",
        "snat_ip": "ALTER TABLE firewall_rules ADD COLUMN snat_ip TEXT",
        "position": "ALTER TABLE firewall_rules ADD COLUMN position DOUBLE PRECISION",
    },
    "vpn_events": {
        # Resolved once, at ingest time (deploy/ingest_logs.py), for
        # 'connected' rows whose address is behind the relay — see
        # app/vpnlog.py's resolve_real_address. Added after vpn_events
        # itself already existed on at least one real install (.10), hence
        # a migration rather than just a column in CREATE TABLE.
        "real_address": "ALTER TABLE vpn_events ADD COLUMN real_address TEXT",
    },
    "servers": {
        # Added after the servers table itself already existed on at
        # least one real install (.10, registered before token expiry was
        # a thing) — existing rows get NULL (never expires) until
        # rotate_server_token gives them a real one, same "opt in on next
        # rotation" behavior as everything else added this way.
        "token_expires_at": "ALTER TABLE servers ADD COLUMN token_expires_at TEXT",
    },
    "users": {
        # Existing rows default to 0, same as a brand-new row — the first
        # login after this deploy just bumps it to 1, same as any other
        # login; the only real-world effect is that every session/token
        # issued before this migration ran (with no "gen" claim at all)
        # stops matching and is treated as logged out — a one-time forced
        # re-login, not a bug.
        "session_generation": "ALTER TABLE users ADD COLUMN session_generation INTEGER NOT NULL DEFAULT 0",
    },
}


def init_db():
    conn = get_conn()
    try:
        conn.execute(SCHEMA)
        for table, columns in _MIGRATIONS.items():
            existing_cols = {
                row["column_name"]
                for row in conn.execute(
                    "SELECT column_name FROM information_schema.columns WHERE table_name = %s",
                    (table,),
                ).fetchall()
            }
            for col, ddl in columns.items():
                if col not in existing_cols:
                    conn.execute(ddl)
        # Rows from before the position column existed (or any row inserted
        # without one) — fall back to id order, which is what they sorted by
        # already.
        conn.execute("UPDATE firewall_rules SET position = id WHERE position IS NULL")
        # One-time bootstrap: this app used to have exactly one hardcoded
        # account, authenticated against ADMIN_USERNAME/ADMIN_PASSWORD_HASH
        # in .env (see config.py). The first time this runs against a users
        # table with nothing in it yet, carry that account over as a real
        # row — every existing install's current login keeps working with
        # zero manual steps, and .env's values become unused dead config
        # from then on (verify_credentials only ever reads the users table
        # once it has at least one row).
        user_count = conn.execute("SELECT COUNT(*) AS count FROM users").fetchone()["count"]
        if user_count == 0 and config.ADMIN_USERNAME and config.ADMIN_PASSWORD_HASH:
            conn.execute(
                "INSERT INTO users (username, password_hash) VALUES (%s, %s)",
                (config.ADMIN_USERNAME, config.ADMIN_PASSWORD_HASH),
            )
        conn.commit()
    finally:
        conn.close()


def insert_rule(rule: dict) -> int:
    conn = get_conn()
    try:
        if rule.get("position") is None:
            # Default: append after everything currently in the table, same
            # as this app's rules have always ended up live via -A anyway.
            max_pos = conn.execute(
                "SELECT COALESCE(MAX(position), 0) AS max_pos FROM firewall_rules"
            ).fetchone()["max_pos"]
            rule = {**rule, "position": max_pos + 1}
        cols = list(rule.keys())
        placeholders = ",".join("%s" for _ in cols)
        sql = f"INSERT INTO firewall_rules ({','.join(cols)}) VALUES ({placeholders}) RETURNING id"
        cur = conn.execute(sql, [rule[c] for c in cols])
        new_id = cur.fetchone()["id"]
        if "id" in rule:
            # GENERATED BY DEFAULT AS IDENTITY (chosen over GENERATED
            # ALWAYS specifically so an explicit id — nothing in this app
            # itself does that, but its own test suite does, for
            # readable fixture data, the same way SQLite's AUTOINCREMENT
            # always allowed) doesn't auto-advance its own sequence when
            # the value came in explicitly rather than from the sequence
            # itself. Without this, the *next* auto-generated insert can
            # collide with an id a caller set by hand — caught live via
            # this file's own test suite once real Postgres exposed it
            # (SQLite never had this failure mode at all).
            _sync_id_sequence(conn, "firewall_rules")
        conn.commit()
        return new_id
    finally:
        conn.close()


def _sync_id_sequence(conn, table: str):
    conn.execute(
        "SELECT setval(pg_get_serial_sequence(%s, 'id'), "
        "GREATEST((SELECT COALESCE(MAX(id), 0) FROM " + table + "), 1))",
        (table,),
    )


def list_rules(enabled_only: bool = False) -> list[dict]:
    conn = get_conn()
    try:
        sql = "SELECT * FROM firewall_rules"
        if enabled_only:
            sql += " WHERE enabled=1"
        sql += " ORDER BY position, id"
        return [dict(r) for r in conn.execute(sql).fetchall()]
    finally:
        conn.close()


def set_positions(mapping: dict[int, float]):
    """Bulk position update for a reorder swap — both rows change together,
    in one transaction, so a crash mid-write can't leave two rules sharing
    (or missing) a position."""
    conn = get_conn()
    try:
        conn.executemany(
            "UPDATE firewall_rules SET position=%s WHERE id=%s",
            [(pos, rule_id) for rule_id, pos in mapping.items()],
        )
        conn.commit()
    finally:
        conn.close()


def get_rule(rule_id: int):
    conn = get_conn()
    try:
        row = conn.execute("SELECT * FROM firewall_rules WHERE id=%s", (rule_id,)).fetchone()
        return dict(row) if row else None
    finally:
        conn.close()


def get_client_block(client_name: str):
    conn = get_conn()
    try:
        row = conn.execute(
            "SELECT * FROM firewall_rules WHERE kind='client_block' AND client_name=%s",
            (client_name,),
        ).fetchone()
        return dict(row) if row else None
    finally:
        conn.close()


def delete_rule(rule_id: int):
    conn = get_conn()
    try:
        conn.execute("DELETE FROM firewall_rules WHERE id=%s", (rule_id,))
        conn.commit()
    finally:
        conn.close()


def set_enabled(rule_id: int, enabled: bool):
    conn = get_conn()
    try:
        conn.execute("UPDATE firewall_rules SET enabled=%s WHERE id=%s", (1 if enabled else 0, rule_id))
        conn.commit()
    finally:
        conn.close()


def get_user(user_id: int):
    conn = get_conn()
    try:
        row = conn.execute("SELECT * FROM users WHERE id=%s", (user_id,)).fetchone()
        return dict(row) if row else None
    finally:
        conn.close()


def get_user_by_username(username: str):
    conn = get_conn()
    try:
        row = conn.execute("SELECT * FROM users WHERE username=%s", (username,)).fetchone()
        return dict(row) if row else None
    finally:
        conn.close()


def list_users() -> list[dict]:
    conn = get_conn()
    try:
        return [dict(r) for r in conn.execute("SELECT * FROM users ORDER BY username").fetchall()]
    finally:
        conn.close()


def count_users() -> int:
    conn = get_conn()
    try:
        return conn.execute("SELECT COUNT(*) AS count FROM users").fetchone()["count"]
    finally:
        conn.close()


def count_admins() -> int:
    conn = get_conn()
    try:
        return conn.execute("SELECT COUNT(*) AS count FROM users WHERE role='admin'").fetchone()["count"]
    finally:
        conn.close()


def insert_user(username: str, password_hash: str, role: str = "admin") -> int:
    conn = get_conn()
    try:
        try:
            cur = conn.execute(
                "INSERT INTO users (username, password_hash, role) VALUES (%s, %s, %s) RETURNING id",
                (username, password_hash, role),
            )
        except psycopg2.errors.UniqueViolation as exc:
            conn.rollback()
            raise ValueError(f"A user named '{username}' already exists.") from exc
        new_id = cur.fetchone()["id"]
        conn.commit()
        return new_id
    finally:
        conn.close()


def bump_session_generation(user_id: int) -> int:
    """Called on every successful login (browser or API) — see the
    session_generation column's own comment on the users table. Returns
    the new value so the caller can embed it as the login's "gen" claim
    immediately, without a second round trip to read it back."""
    conn = get_conn()
    try:
        cur = conn.execute(
            "UPDATE users SET session_generation = session_generation + 1 WHERE id = %s RETURNING session_generation",
            (user_id,),
        )
        new_gen = cur.fetchone()["session_generation"]
        conn.commit()
        return new_gen
    finally:
        conn.close()


def delete_user(user_id: int):
    conn = get_conn()
    try:
        conn.execute("DELETE FROM users WHERE id=%s", (user_id,))
        conn.commit()
    finally:
        conn.close()


def delete_user_guarded(user_id: int) -> tuple[dict | None, str | None]:
    """Atomically check-and-delete in one locked transaction. A separate
    count_admins()-then-delete_user() pair (the original implementation)
    has a real TOCTOU race: gunicorn runs multiple worker processes, so
    two near-simultaneous requests can each read the same pre-delete
    admin count before either commits, both see "not the last admin",
    and both proceed — landing on zero admins even though each check was
    individually correct for the state it saw at the time. Reproduced
    live against an isolated DB copy before this existed.

    SELECT ... FOR UPDATE locks every admin row before counting them, so
    a second concurrent call blocks until the first's delete (or
    refusal) fully commits, then reads the real, post-delete set — same
    fix shape as the firewall self-lockout guards, just for a race
    between two different admins instead of one admin's own request
    sequence. (Ported from SQLite's whole-database BEGIN IMMEDIATE lock
    to Postgres's row-level locking — see locked_transaction's
    docstring.)

    Returns (deleted_row, None) on success, or (target_row_or_None,
    reason) where reason is 'not_found' or 'last_admin' on refusal —
    the caller still gets the row (for its username) even when refused,
    except when it never existed at all."""
    with locked_transaction() as conn:
        row = conn.execute("SELECT * FROM users WHERE id=%s", (user_id,)).fetchone()
        if not row:
            return None, "not_found"
        if row["role"] == "admin":
            admin_rows = conn.execute("SELECT id FROM users WHERE role='admin' FOR UPDATE").fetchall()
            if len(admin_rows) <= 1:
                return dict(row), "last_admin"
        conn.execute("DELETE FROM users WHERE id=%s", (user_id,))
        return dict(row), None


def set_user_password(user_id: int, password_hash: str):
    conn = get_conn()
    try:
        conn.execute("UPDATE users SET password_hash=%s WHERE id=%s", (password_hash, user_id))
        conn.commit()
    finally:
        conn.close()


# How long audit_log rows stick around before add_audit opportunistically
# prunes them — long enough to matter for a real incident review, short
# enough that the table doesn't grow forever from background noise. That
# noise is real, not hypothetical: the login page is now reachable from
# the public internet via the relay, and every failed attempt (including
# ones from bots that have no idea this is PiVPN, just scanning) writes
# a row here — see login_failures for the separate, shorter-lived table
# that actually drives rate-limiting.
AUDIT_LOG_RETENTION_DAYS = 90


def add_audit(actor: str, action: str, target: str = "", result: str = "ok", detail: str = ""):
    # Cutoff/insert timestamp both computed in Python (datetime.now(),
    # the box's actual local time, Asia/Phnom_Penh) rather than a SQL
    # date function — same reasoning as before: everything this column
    # is ever compared against elsewhere in the app is also a
    # Python-formatted string in this exact format, so there's one
    # single source of truth for "now" instead of the app and the
    # database needing to agree on a timezone.
    conn = get_conn()
    try:
        cutoff = (datetime.now() - timedelta(days=AUDIT_LOG_RETENTION_DAYS)).strftime("%Y-%m-%d %H:%M:%S")
        conn.execute("DELETE FROM audit_log WHERE ts < %s", (cutoff,))
        conn.execute(
            "INSERT INTO audit_log (ts, actor, action, target, result, detail) VALUES (%s,%s,%s,%s,%s,%s)",
            (datetime.now().strftime("%Y-%m-%d %H:%M:%S"), actor, action, target, result, (detail or "")[:500]),
        )
        conn.commit()
    finally:
        conn.close()


def list_audit(limit: int = 200) -> list[dict]:
    conn = get_conn()
    try:
        rows = conn.execute(
            "SELECT * FROM audit_log ORDER BY id DESC LIMIT %s", (limit,)
        ).fetchall()
        return [dict(r) for r in rows]
    finally:
        conn.close()


def record_login_failure(ip: str):
    """Also opportunistically prunes anything old enough that no lockout
    window could ever care about it again — no separate cleanup job
    needed for a table that only ever grows one row per failed attempt.
    Cutoff computed in Python (UTC, matching the original SQLite
    CURRENT_TIMESTAMP default's own UTC-ness) so it stays comparable
    against count_recent_login_failures' own Python-computed window —
    both sides need to agree on a clock, same reasoning as add_audit
    above, just UTC here instead of local time since that's what the
    stored ts values' own DEFAULT already produces."""
    from datetime import timezone

    conn = get_conn()
    try:
        cutoff = (datetime.now(timezone.utc) - timedelta(hours=1)).strftime("%Y-%m-%d %H:%M:%S")
        conn.execute("DELETE FROM login_failures WHERE ts < %s", (cutoff,))
        conn.execute("INSERT INTO login_failures (ip, ts) VALUES (%s, %s)",
                     (ip, datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%S")))
        conn.commit()
    finally:
        conn.close()


def count_recent_login_failures(ip: str, window_seconds: int) -> int:
    from datetime import timezone

    conn = get_conn()
    try:
        cutoff = (datetime.now(timezone.utc) - timedelta(seconds=window_seconds)).strftime("%Y-%m-%d %H:%M:%S")
        return conn.execute(
            "SELECT COUNT(*) AS count FROM login_failures WHERE ip = %s AND ts > %s",
            (ip, cutoff),
        ).fetchone()["count"]
    finally:
        conn.close()


def clear_login_failures(ip: str):
    conn = get_conn()
    try:
        conn.execute("DELETE FROM login_failures WHERE ip = %s", (ip,))
        conn.commit()
    finally:
        conn.close()


def list_audit_by_actions(actions: tuple[str, ...], limit: int = 200) -> list[dict]:
    conn = get_conn()
    try:
        placeholders = ",".join("%s" for _ in actions)
        rows = conn.execute(
            f"SELECT * FROM audit_log WHERE action IN ({placeholders}) ORDER BY id DESC LIMIT %s",
            (*actions, limit),
        ).fetchall()
        return [dict(r) for r in rows]
    finally:
        conn.close()


def list_audit_page(
    q: str | None = None, page: int = 1, page_size: int = 50, since: str | None = None,
    actions: tuple[str, ...] | None = None,
) -> tuple[list[dict], int]:
    """Most recent first, server-side paginated and searched — backs the
    Logs page's Activity and User Auth tabs (Activity: actions=None, no
    restriction; User Auth: actions=AUTH_ACTIONS). Returns (rows,
    total_matching_count); see list_vpn_events_page's docstring for `q`
    and `since`'s exact contract (same conventions, same 'YYYY-MM-DD
    HH:MM:SS' cutoff format for `since`, since add_audit stores `ts` the
    same way)."""
    conn = get_conn()
    try:
        clauses = []
        params: list = []
        if actions:
            placeholders = ",".join("%s" for _ in actions)
            clauses.append(f"action IN ({placeholders})")
            params += list(actions)
        if q:
            like = f"%{_escape_like(q)}%"
            clauses.append(
                "(actor LIKE %s ESCAPE '\\' OR action LIKE %s ESCAPE '\\' OR target LIKE %s ESCAPE '\\' "
                "OR result LIKE %s ESCAPE '\\' OR detail LIKE %s ESCAPE '\\')"
            )
            params += [like, like, like, like, like]
        if since:
            clauses.append("ts >= %s")
            params.append(since)
        where_sql = ("WHERE " + " AND ".join(clauses)) if clauses else ""
        total = conn.execute(f"SELECT COUNT(*) AS count FROM audit_log {where_sql}", params).fetchone()["count"]
        rows = conn.execute(
            f"SELECT * FROM audit_log {where_sql} ORDER BY id DESC LIMIT %s OFFSET %s",
            [*params, page_size, (page - 1) * page_size],
        ).fetchall()
        return [dict(r) for r in rows], total
    finally:
        conn.close()


def get_cached_ip_org(ip: str) -> tuple[bool, str | None]:
    """(found, org) — found=False means this IP has never been looked up
    at all (org=None alone can't distinguish that from "looked up, found
    nothing"), which is exactly what a cache-fill caller needs to know."""
    conn = get_conn()
    try:
        row = conn.execute("SELECT org FROM ip_org_cache WHERE ip = %s", (ip,)).fetchone()
        return (True, row["org"]) if row else (False, None)
    finally:
        conn.close()


def cache_ip_org(ip: str, org: str | None):
    conn = get_conn()
    try:
        conn.execute(
            "INSERT INTO ip_org_cache (ip, org) VALUES (%s, %s) "
            "ON CONFLICT (ip) DO UPDATE SET org = excluded.org, looked_up_at = to_char(now(), 'YYYY-MM-DD HH24:MI:SS')",
            (ip, org),
        )
        conn.commit()
    finally:
        conn.close()


def insert_vpn_events(rows: list[tuple[str, str, str, str, str, str | None]]):
    """Each row: (ts, event, client, address, detail, real_address).
    ON CONFLICT DO NOTHING (ported from SQLite's INSERT OR IGNORE) so a
    duplicate ingest of an already-seen line (see the table's own
    comment) is silently a no-op rather than a duplicate row or an
    aborted batch."""
    if not rows:
        return
    conn = get_conn()
    try:
        conn.executemany(
            "INSERT INTO vpn_events (ts, event, client, address, detail, real_address) "
            "VALUES (%s, %s, %s, %s, %s, %s) "
            "ON CONFLICT (ts, event, client, address, detail) DO NOTHING",
            rows,
        )
        conn.commit()
    finally:
        conn.close()


def _escape_like(s: str) -> str:
    """Escapes SQL LIKE's own wildcard characters in a *user-supplied*
    search term, so e.g. a client name containing a literal underscore
    (a valid character per pivpn_ctl.CLIENT_NAME_RE) doesn't get
    interpreted as LIKE's own single-character wildcard. Paired with
    ESCAPE '\\' at every call site below."""
    return s.replace("\\", "\\\\").replace("%", "\\%").replace("_", "\\_")


def list_vpn_events_page(
    q: str | None = None, page: int = 1, page_size: int = 50, since: str | None = None
) -> tuple[list[dict], int]:
    """Most recent first, server-side paginated and searched — for the
    flat VPN Sessions tab (app/vpnlog.py's list_sessions). Returns (rows,
    total_matching_count) so the caller can render real page numbers
    instead of guessing from just one page's worth of rows.

    `q`, if given, matches as a case-insensitive substring against any of
    the columns actually shown in that tab (event/client/address/detail)
    — same "any column" search the old client-side filter used to do.

    `since`, if given, is a 'YYYY-MM-DD HH:MM:SS' cutoff (same format `ts`
    is stored in — see vpnlog._format_ts) — only rows at or after it are
    returned. A plain string comparison works because every `ts` in this
    table shares that one zero-padded format."""
    conn = get_conn()
    try:
        clauses = []
        params: list = []
        if q:
            like = f"%{_escape_like(q)}%"
            clauses.append(
                "(event LIKE %s ESCAPE '\\' OR client LIKE %s ESCAPE '\\' "
                "OR address LIKE %s ESCAPE '\\' OR detail LIKE %s ESCAPE '\\')"
            )
            params += [like, like, like, like]
        if since:
            clauses.append("ts >= %s")
            params.append(since)
        where_sql = ("WHERE " + " AND ".join(clauses)) if clauses else ""
        total = conn.execute(f"SELECT COUNT(*) AS count FROM vpn_events {where_sql}", params).fetchone()["count"]
        rows = conn.execute(
            f"SELECT ts, event, client, address, detail, real_address FROM vpn_events "
            f"{where_sql} ORDER BY ts DESC, id DESC LIMIT %s OFFSET %s",
            [*params, page_size, (page - 1) * page_size],
        ).fetchall()
        return [dict(r) for r in rows], total
    finally:
        conn.close()


def list_vpn_events(limit: int = 50000) -> list[dict]:
    """Oldest first — matches what app/vpnlog.py's pairing logic expects
    (it walks events in the order they actually happened), same contract
    the old live-journalctl path had. Default limit is a generous safety
    cap, not the real bound — prune_old_logs already keeps this table down
    to roughly a month's worth (~13k rows/week observed live), and taking
    the *oldest* N here (not the most recent) would be wrong once a cap
    this low ever actually binds, so it's set well above any realistic
    30-day row count instead of relying on that not mattering."""
    conn = get_conn()
    try:
        rows = conn.execute(
            "SELECT ts, event, client, address, detail, real_address FROM vpn_events "
            "ORDER BY ts ASC, id ASC LIMIT %s",
            (limit,),
        ).fetchall()
        return [dict(r) for r in rows]
    finally:
        conn.close()


def insert_traffic_flows(rows: list[tuple]):
    """Each row: (ts, src, dst, dst_org, client, proto, sport, dport,
    in_if, out_if). ON CONFLICT DO NOTHING for the same reprocessing-
    safety reason as insert_vpn_events above."""
    if not rows:
        return
    conn = get_conn()
    try:
        conn.executemany(
            "INSERT INTO traffic_flows "
            "(ts, src, dst, dst_org, client, proto, sport, dport, in_if, out_if) "
            "VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s) "
            "ON CONFLICT (ts, src, dst, proto, sport, dport) DO NOTHING",
            rows,
        )
        conn.commit()
    finally:
        conn.close()


def list_traffic_flows(
    q: str | None = None, page: int = 1, page_size: int = 50, since: str | None = None
) -> tuple[list[dict], int]:
    """Most recent first, server-side paginated and searched — this is a
    display list, unlike list_vpn_events above (which feeds a pairing
    algorithm that wants chronological order). Returns (rows,
    total_matching_count); see list_vpn_events_page's docstring for why,
    and for what `since` expects."""
    conn = get_conn()
    try:
        clauses = []
        params: list = []
        if q:
            like = f"%{_escape_like(q)}%"
            clauses.append(
                "(client LIKE %s ESCAPE '\\' OR src LIKE %s ESCAPE '\\' "
                "OR dst LIKE %s ESCAPE '\\' OR dst_org LIKE %s ESCAPE '\\' "
                "OR proto LIKE %s ESCAPE '\\' OR dport LIKE %s ESCAPE '\\')"
            )
            params += [like, like, like, like, like, like]
        if since:
            clauses.append("ts >= %s")
            params.append(since)
        where_sql = ("WHERE " + " AND ".join(clauses)) if clauses else ""
        total = conn.execute(f"SELECT COUNT(*) AS count FROM traffic_flows {where_sql}", params).fetchone()["count"]
        rows = conn.execute(
            f"SELECT ts, src, dst, dst_org, client, proto, sport, dport, in_if, out_if "
            f"FROM traffic_flows {where_sql} ORDER BY ts DESC, id DESC LIMIT %s OFFSET %s",
            [*params, page_size, (page - 1) * page_size],
        ).fetchall()
        return [dict(r) for r in rows], total
    finally:
        conn.close()


def insert_system_log_lines(rows: list[tuple[str, str, str]]):
    """Each row: (ts, process, message). ON CONFLICT DO NOTHING for the
    same reprocessing-safety reason as insert_vpn_events — journalctl
    --cursor-file can re-emit the last-seen line on the next run."""
    if not rows:
        return
    conn = get_conn()
    try:
        conn.executemany(
            "INSERT INTO system_log_lines (ts, process, message) VALUES (%s, %s, %s) "
            "ON CONFLICT (ts, process, message) DO NOTHING",
            rows,
        )
        conn.commit()
    finally:
        conn.close()


def list_system_log_page(
    q: str | None = None, page: int = 1, page_size: int = 50, since: str | None = None
) -> tuple[list[dict], int]:
    """Most recent first, server-side paginated and searched — same
    conventions as list_vpn_events_page/list_traffic_flows (see their
    docstrings for what `q`/`since` expect)."""
    conn = get_conn()
    try:
        clauses = []
        params: list = []
        if q:
            like = f"%{_escape_like(q)}%"
            clauses.append("(process LIKE %s ESCAPE '\\' OR message LIKE %s ESCAPE '\\')")
            params += [like, like]
        if since:
            clauses.append("ts >= %s")
            params.append(since)
        where_sql = ("WHERE " + " AND ".join(clauses)) if clauses else ""
        total = conn.execute(
            f"SELECT COUNT(*) AS count FROM system_log_lines {where_sql}", params
        ).fetchone()["count"]
        rows = conn.execute(
            f"SELECT ts, process, message FROM system_log_lines {where_sql} "
            f"ORDER BY ts DESC, id DESC LIMIT %s OFFSET %s",
            [*params, page_size, (page - 1) * page_size],
        ).fetchall()
        return [dict(r) for r in rows], total
    finally:
        conn.close()


def _token_expiry() -> str:
    return (datetime.now() + timedelta(days=config.AGENT_TOKEN_TTL_DAYS)).strftime("%Y-%m-%d %H:%M:%S")


def create_server(name: str) -> tuple[int, str]:
    """Registers a new remote agent box and returns (id, raw_token) — the
    raw token is only ever available here, at creation time; only its
    hash is persisted (see servers.token_hash). Caller (manage_servers.py)
    is responsible for showing it to the operator exactly once, to paste
    into that box's agent .env as AGENT_TOKEN."""
    token = secrets.token_urlsafe(32)
    conn = get_conn()
    try:
        try:
            cur = conn.execute(
                "INSERT INTO servers (name, token_hash, token_expires_at) VALUES (%s, %s, %s) RETURNING id",
                (name, generate_password_hash(token), _token_expiry()),
            )
        except psycopg2.errors.UniqueViolation as exc:
            conn.rollback()
            raise ValueError(f"A server named '{name}' already exists.") from exc
        new_id = cur.fetchone()["id"]
        conn.commit()
        return new_id, token
    finally:
        conn.close()


def rotate_server_token(name: str) -> tuple[int, str] | None:
    """Issues a fresh token (and a fresh expiry) for an already-registered
    agent, without touching its id or name — the renewal path once
    AGENT_TOKEN_TTL_DAYS is approaching, or any time earlier if a token is
    suspected to have leaked. Returns None if no server has that name."""
    token = secrets.token_urlsafe(32)
    conn = get_conn()
    try:
        cur = conn.execute(
            "UPDATE servers SET token_hash=%s, token_expires_at=%s WHERE name=%s RETURNING id",
            (generate_password_hash(token), _token_expiry(), name),
        )
        row = cur.fetchone()
        if not row:
            return None
        conn.commit()
        return row["id"], token
    finally:
        conn.close()


def verify_server_token(server_id: int, token: str) -> str:
    """Returns 'ok', 'invalid' (wrong token or no such server_id), or
    'expired' — a string rather than bool so hub_gateway.py can audit-log
    *why* a hello was rejected, not just that it was."""
    conn = get_conn()
    try:
        row = conn.execute(
            "SELECT token_hash, token_expires_at FROM servers WHERE id=%s", (server_id,)
        ).fetchone()
        if not row or not check_password_hash(row["token_hash"], token):
            return "invalid"
        if row["token_expires_at"] and row["token_expires_at"] < datetime.now().strftime("%Y-%m-%d %H:%M:%S"):
            return "expired"
        return "ok"
    finally:
        conn.close()


def get_server_by_name(name: str) -> dict | None:
    conn = get_conn()
    try:
        row = conn.execute("SELECT * FROM servers WHERE name=%s", (name,)).fetchone()
        return dict(row) if row else None
    finally:
        conn.close()


def touch_server_last_seen(server_id: int):
    conn = get_conn()
    try:
        conn.execute(
            "UPDATE servers SET last_seen_at=to_char(now(), 'YYYY-MM-DD HH24:MI:SS') WHERE id=%s",
            (server_id,),
        )
        conn.commit()
    finally:
        conn.close()


def prune_old_logs(days: int):
    """Deletes vpn_events/traffic_flows/system_log_lines rows older than
    `days` — without this, traffic_flows and (especially) system_log_lines
    grow without bound (thousands of rows/day at this app's observed
    traffic rate, and system_log_lines covers the *entire* journal, not
    just VPN-relevant lines), unlike journald's own log rotation which did
    this for free under the old live-parsing design. Called once per
    ingest_logs.py run, not on any request path. (The dedicated daily
    prune_db.sh/systemd timer also covers this at a 30-day window — this
    per-run call and that one are redundant by design, not a conflict:
    whichever runs first wins, harmlessly.)"""
    conn = get_conn()
    try:
        cutoff = (datetime.now() - timedelta(days=days)).strftime("%Y-%m-%d %H:%M:%S")
        conn.execute("DELETE FROM vpn_events WHERE ts < %s", (cutoff,))
        conn.execute("DELETE FROM traffic_flows WHERE ts < %s", (cutoff,))
        conn.execute("DELETE FROM system_log_lines WHERE ts < %s", (cutoff,))
        conn.commit()
    finally:
        conn.close()
